# Generated by Django 5.2.16 on 2026-07-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="모임명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("vote_start", models.DateField(verbose_name="투표 시작일")),
                ("vote_end", models.DateField(verbose_name="투표 종료일")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VOTING", "요일 투표중"),
                            ("CONFIRMED", "모임 확정"),
                            ("FINISHED", "종료"),
                        ],
                        default="VOTING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
