# Generated by Django 5.2.16 on 2026-07-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meeting",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "모임",
                "verbose_name_plural": "모임",
            },
        ),
        migrations.AddField(
            model_name="meeting",
            name="location",
            field=models.CharField(blank=True, max_length=100, verbose_name="장소"),
        ),
        migrations.AddField(
            model_name="meeting",
            name="meal_type",
            field=models.CharField(
                blank=True,
                choices=[("LUNCH", "점심"), ("DINNER", "저녁")],
                max_length=10,
                null=True,
                verbose_name="식사 시간",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="meeting_date",
            field=models.DateField(blank=True, null=True, verbose_name="최종 날짜"),
        ),
        migrations.AddField(
            model_name="meeting",
            name="meeting_time",
            field=models.TimeField(blank=True, null=True, verbose_name="모임 시간"),
        ),
        migrations.AddField(
            model_name="meeting",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="status",
            field=models.CharField(
                choices=[
                    ("VOTING", "요일 투표중"),
                    ("CONFIRMED", "모임 확정"),
                    ("FINISHED", "종료"),
                ],
                default="VOTING",
                max_length=20,
                verbose_name="상태",
            ),
        ),
    ]
