# Generated by Django 5.2.16 on 2026-07-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0003_availabilityvote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availabilityvote",
            name="weekday",
            field=models.CharField(
                choices=[
                    ("MON", "월요일"),
                    ("TUE", "화요일"),
                    ("WED", "수요일"),
                    ("THU", "목요일"),
                    ("FRI", "금요일"),
                    ("SAT", "토요일"),
                ],
                max_length=3,
            ),
        ),
    ]
