# Generated by Django 5.2.16 on 2026-07-10 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0004_alter_availabilityvote_weekday"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.CharField(
                        choices=[
                            ("MON", "월요일"),
                            ("TUE", "화요일"),
                            ("WED", "수요일"),
                            ("THU", "목요일"),
                            ("FRI", "금요일"),
                            ("SAT", "토요일"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[("LUNCH", "점심"), ("DINNER", "저녁")], max_length=10
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="meeting.meeting",
                    ),
                ),
            ],
            options={
                "unique_together": {("meeting", "weekday", "meal_type")},
            },
        ),
    ]
