# Generated by Django 5.2.16 on 2026-07-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0006_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="status",
            field=models.CharField(
                choices=[
                    ("VOTING", "요일 투표중"),
                    ("CONFIRMED", "모임 확정"),
                    ("ATTENDANCE", "참석 여부 투표중"),
                    ("FINISHED", "종료"),
                ],
                default="VOTING",
                max_length=20,
                verbose_name="상태",
            ),
        ),
    ]
