# Generated by Django 5.2.16 on 2026-08-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0007_alter_meeting_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="availabilityvote",
            name="is_unavailable",
            field=models.BooleanField(default=False, verbose_name="시간 안됨"),
        ),
        migrations.AlterField(
            model_name="availabilityvote",
            name="meal_type",
            field=models.CharField(
                blank=True,
                choices=[("LUNCH", "점심"), ("DINNER", "저녁")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="availabilityvote",
            name="weekday",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MON", "월요일"),
                    ("TUE", "화요일"),
                    ("WED", "수요일"),
                    ("THU", "목요일"),
                    ("FRI", "금요일"),
                    ("SAT", "토요일"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
