# Generated by Django 5.2.16 on 2026-07-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="이름")),
                (
                    "campus",
                    models.CharField(
                        choices=[("JEONJU", "전주"), ("IKSAN", "익산")],
                        max_length=20,
                        verbose_name="캠퍼스",
                    ),
                ),
                (
                    "grade",
                    models.CharField(blank=True, max_length=20, verbose_name="학년"),
                ),
                (
                    "major",
                    models.CharField(blank=True, max_length=50, verbose_name="전공"),
                ),
                (
                    "favorite_food",
                    models.TextField(
                        blank=True,
                        help_text="쉼표(,)로 구분해서 입력해주세요.",
                        verbose_name="먹고 싶은 음식",
                    ),
                ),
                (
                    "disliked_food",
                    models.TextField(blank=True, verbose_name="못 먹는 음식"),
                ),
                ("allergy", models.TextField(blank=True, verbose_name="알레르기")),
                (
                    "expectation",
                    models.TextField(blank=True, verbose_name="방학 기대하는 점"),
                ),
                (
                    "prayer_request",
                    models.TextField(blank=True, verbose_name="기도제목"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "참여자",
                "verbose_name_plural": "참여자",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "campus"), name="unique_participant"
                    )
                ],
            },
        ),
    ]
