# Generated by Django 5.2.16 on 2026-07-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="campus",
            field=models.CharField(
                choices=[("JEONJUUNIV", "전주대"), ("VISIONUNIV", "비전대")],
                max_length=20,
                verbose_name="캠퍼스",
            ),
        ),
    ]
