# Generated by Django 5.2.16 on 2026-07-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0002_alter_participant_campus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="allergy",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="expectation",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="major",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="prayer_request",
        ),
        migrations.AddField(
            model_name="participant",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="활성 여부"),
        ),
        migrations.AddField(
            model_name="participant",
            name="student_id",
            field=models.CharField(blank=True, max_length=20, verbose_name="학번"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="campus",
            field=models.CharField(
                choices=[
                    ("JEONJUUNIV", "전주대"),
                    ("VISIONUNIV", "비전대"),
                    ("JESUSUNIV", "예수대"),
                    ("KIJEONUNIV", "기전대"),
                    ("AFUNIV", "한국농수산대"),
                ],
                max_length=20,
                verbose_name="캠퍼스",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="disliked_food",
            field=models.TextField(
                blank=True,
                help_text="쉼표(,)로 구분해서 입력해주세요.",
                verbose_name="못 먹는 음식",
            ),
        ),
    ]
